### ISSUE TITLE
[Feature Request] Implement GetSearchAttributesRequest

### ISSUE THREAD

**Issue by Rastusik** [temporalio/sdk-php#102]
I want to be able to search the workflows and activities programatically (it is already possible in java)

> I'm currently integrating temporal and I want to be able to write integration tests, where I want to check the states of some workflows. Currently I need to run shell tctl command from PHP to get the data I need. Or maybe I just didn't notice where the API for this is hidden.

**Describe the solution you'd like**

> It would be sufficient to get the same functionality as in the java sdk

**Comment by wolfy-j** [comment]
Have you checked the ServiceClient? https://github.com/temporalio/sdk-php/blob/master/src/Client/WorkflowClientInterface.php#L22

It has all the Temporal API.

**Comment by Rastusik** [comment]
yes, sure, but it would be really nice to have better support for search than just creating grpc requests manually

**Comment by wolfy-j** [comment]
Sure. Can you point me to the Java reference you are looking for?

**Comment by Rastusik** [comment]
https://github.com/temporalio/sdk-java/blob/master/temporal-sdk/src/test/java/io/temporal/workflow/SearchAttributesTest.java

**Comment by Rastusik** [comment]
now when I look at it, it seems that the Java sdk doesn't have this functionality either, sorry for the confusion... so basically it would be nice to just pass the query to some client instance and get results

**Comment by wolfy-j** [comment]
Got it. For now, please stick to GRPC or create your wrapper at top of it. We can think about easier to use search API after dealing with the rest of the backlog.

**Comment by wolfy-j** [comment]
Sounds like the solution is to use a user-defined GRPC wrapper as in Java. Closing for now.
