### ISSUE TITLE
[Question] Injecting custom reader into worker factory.

### ISSUE THREAD

**Issue by Zylius** [temporalio/sdk-php#110]
Hello,

Is there any way to inject a custom reader into WorkerFactory/Worker?

We're switching over to temporal and I'd like to register the old activities/workflows using our old logic for now and move over to Temporal attributes as new activites/workflows appear.

But it seems, cause of all the final classes the only way to do this would be to copy over the WorkerFactory completely.

Is this https://github.com/temporalio/sdk-php/issues/88 dealing with the same issue?

Thanks for help!

**Comment by wolfy-j** [comment]
Can you elaborate? What are you trying to achieve? 

You have to manually register each activity, so you can pull it from any DI container.

**Comment by Zylius** [comment]
Yes sure, here's an example:
``` php
#!/usr/bin/env php
<?php

use Temporal\WorkerFactory;

class SimpleWorker
{
    public function simpleActivityMethod(): string
    {
        return 'simple_string';
    }
}

$existingData = [
    SimpleWorker::class => [
        'methodNames' => [
            'simpleActivityMethod' => 'simpleMethod'
        ],
        'prefix' => 'simple_'
    ]
];

$factory = WorkerFactory::create();
$worker = $factory->newWorker();

// How do I register the activity, without PHP8 attributes, so that its info gets loaded from
// $existingData variable ? 
$worker->registerActivityImplementations(new SimpleWorker());

$factory->run();
```
And a more elaborate explanation:  lets say I'm adding an Activity object to a Worker using [registerActivityImplementations](https://github.com/temporalio/sdk-php/blob/master/src/Worker/Worker.php#L133). It reads the activity method groups, names and other info based on PHP 8 style attributes. Since the Worker is created using Worker Factory it has a fixed reader implementation (currently [SelectiveReader or AttributeReader](https://github.com/temporalio/sdk-php/blob/f53f1627f63fca73bd0e533831a8104bacd44309/src/DataConverter/JsonConverter.php#L214)).

Lets say I have the activity method names list and activity prefixes in some array parameter in my DI (not PHP8 style attributes). How do I force [ActivityReader](https://github.com/temporalio/sdk-php/blob/f53f1627f63fca73bd0e533831a8104bacd44309/src/Internal/Declaration/Reader/ActivityReader.php) to read it from the array parameter instead of the PHP8 attributes?

I was postulating that you could inject your own Reader instance into the WorkerFactory. But it's final and impossible. The only other two solutions I could think off would be:
1. Copying the whole WorkerFactory over to my application, so I could inject my own Reader.
2. Using Ocramius proxies  to create stub classes with PHP8 attributes generated.

Both of these solutions seem to have issues with maintenance and simplicity.

I'm doing this in order to let our `old style activities` remain the same, while registering them with temporal.We have lots of activites and adding attributes to each and every one would be bothersome. Though, if it can't be helped we will do it :)

I hope this is clearer, thank you!

**Comment by wolfy-j** [comment]
We are talking internally about how to expose it easier for you. For now, I can recommend you to wrap activities.

**Comment by wolfy-j** [comment]
Can making Factory non final help you to solve your case for now?

**Comment by Zylius** [comment]
Hello, sorry for the late replied missed the notification.

It definitely would! I would then be able to specify my own reader.

**Comment by Zylius** [comment]
Just double checked it and found another issuue. I would also need 

```php
    /**
     * @return ReaderInterface
     */
    private function createReader(): ReaderInterface
    {
        if (\interface_exists(Reader::class)) {
            return new SelectiveReader([new AnnotationReader(), new AttributeReader()]);
        }

        return new AttributeReader();
    }
``` 

To be protected, to be able to override it and inject my own reader nicely. The best option of course would be if I could override the default reader with my own through constructor, just like it's done with DataConverter currently.

```php
    public static function create(
        DataConverterInterface $converter = null,
        RPCConnectionInterface $rpc = null
    ): WorkerFactoryInterface {
        return new self(
            $converter ?? DataConverter::createDefault(),
            $rpc ?? Goridge::create()
        );
    }
 ```


Proposed:

```php
    public static function create(
        DataConverterInterface $converter = null,
        RPCConnectionInterface $rpc = null,
        ReaderInterface $reader = null
    ): WorkerFactoryInterface {
        return new self(
            $converter ?? DataConverter::createDefault(),
            $rpc ?? Goridge::create(),
            $reader ?? self::createReader() // This method can be static since it doesn't use anything from the instance anyways.
        );
    }
 ```

**Comment by wolfy-j** [comment]
We would gladly appreciate a PR for this issue :)

**Comment by Zylius** [comment]
Will do one ;)
