### ISSUE TITLE
[Bug] Parent workflow not completed or failed, when start child workflow execution failed

### ISSUE THREAD

**Issue by khoerintus** [temporalio/sdk-php#113]
**Describe the bug**
Parent workflow is not completed or failed, when start child workflow execution failed.
I am using this samples code:
https://github.com/khoerintus/samples-php/tree/master/app/src/Child

**To Reproduce**
1. First attempt, start parent workflow and it will start child workflow with workflow id
2. Then the parent workflow will completed and child workflow will completed as expected
![Screenshot from 2021-06-17 20-29-27](https://user-images.githubusercontent.com/9275991/122406082-c6b3e380-cfaa-11eb-9b1a-445cab86d2d7.png)
![Screenshot from 2021-06-17 20-31-36](https://user-images.githubusercontent.com/9275991/122406432-0aa6e880-cfab-11eb-8ad5-366f9b612183.png)

3. Second attempt, start parent workflow and it will start child workflow with the same workflow id 
4. But the parent workflow status: Running, with StartChildWorkflowExecutionFailed event because of START_CHILD_WORKFLOW_EXECUTION_FAILED_CAUSE_WORKFLOW_ALREADY_EXISTS
![Screenshot from 2021-06-17 20-30-39](https://user-images.githubusercontent.com/9275991/122406342-f9f67280-cfaa-11eb-87cb-4d759f467e83.png)
![Screenshot from 2021-06-17 20-30-45](https://user-images.githubusercontent.com/9275991/122406354-fb279f80-cfaa-11eb-9558-35b2fc71fcb1.png)
5. Workflow instance will stuck at running, and the last event is WorkflowTaskCompleted until it timeout.

**Expected behavior**
I expected to see workflow instance status is completed.
But the workflow instance status is running until it timeout.
If I do not catch the child workflow execution, then I expect that workflow instance status is failed.

**Versions (please complete the following information where relevant):**
 - OS: Linux
 - Temporal Version: 1.9.2
 - are you using Docker or Kubernetes or building Temporal from source? I am using Docker
 - RR version: rr version 2.2.1 (build time: 2021-05-13T18:00:32+0000, go1.16.4)

**Comment by wolfy-j** [comment]
We planned to take a look at this issue next week.

**Comment by wolfy-j** [comment]
FYI, we are working on the 1.1 milestone where we are going to change the way how workers defined on the Golang side. It should provide extra bits of performance and better scalabiltiy.

**Comment by wolfy-j** [comment]
Fixed in https://github.com/temporalio/roadrunner-temporal/pull/77
