### ISSUE TITLE
[Bug] Wrong exception trace

### ISSUE THREAD

**Issue by xepozz** [temporalio/sdk-php#116]
I'm trying to run Temporal with Symfony application and have problem with error tracing.

1. I'm trying to run non-existent activity method (it exists, but report isn't about that)

I expect to see line in **workflow** where it calls, but I get error on **call workflow method** line and some vendor artefacts. See image

![image](https://user-images.githubusercontent.com/6815714/124363122-22849a80-dc42-11eb-80d0-cdfb79ab2952.png)

---

When I'm trying to roll the same behaviour from code similar to [workshop](https://github.com/wolfy-j/temporal-workshop) I get the following stacktrace:

![image](https://user-images.githubusercontent.com/6815714/124363238-d128db00-dc42-11eb-91b5-1363593abced.png)
As you see `sdk` catches needed lines into stacktrace.

Similar situation when I dump exception directly in `\Temporal\Internal\Client\WorkflowStub::mapWorkflowFailureToException`
![image](https://user-images.githubusercontent.com/6815714/124363319-3086eb00-dc43-11eb-9149-2fda7258b907.png)

---

But as you can see in previous screenshot it's placed in `originalStackTrace` property.
Property `trace` doesn't contain that information so it's displays wrong.

Is it expected behaviour? Would be good to see "original stack trace" in usual "trace" property.

**Comment by wolfy-j** [comment]
Hi, unfortunately, it is not possible to overwrite the PHP exception trace as it possible in Java. So the only option (from our perspective) was to include it into the originalStackTrace. 

Ideally, we need to train exception renderers (or for example Sentry) to understand such types of exceptions and display them. This is partially important when an exception comes from another stack, you can't render something which is not within your codebase.

So this is an excepted behaviour but ideally we need some sugar to make it easier to read.

**Comment by rustatian** [comment]
Closing as answered
