### ISSUE TITLE
[Bug] Wrong activity response type

### ISSUE THREAD

**Issue by xepozz** [temporalio/sdk-php#117]
**Describe the bug**
I send an array from my activity as a result, but in promise step **then** I get **stdClass** instead of array.

**To Reproduce**
1. Create activity that will send an associative array.
2. Create workflow where you call activity and add post-processing in **then** step.
3. Try to get value from **result** as if it array.

**Expected behavior**
I get value

**Expected behavior**
I get an error `PanicError: Cannot use object of type stdClass as array (type: Error, retryable: true)`

**Screenshots/Terminal ouput**
![image](https://user-images.githubusercontent.com/6815714/125174609-46f6ee80-e1cf-11eb-88ce-09608ec4c7a0.png)

You can use this snippet:
```php
#[\Temporal\Activity\ActivityInterface(prefix: "app.")]
class CommonActivity
{
    public function slow(string $name): array
    {
        return [
            'result' => 'Hello, ' . $name,
        ];
    }
}
```

```php
#[\Temporal\Workflow\WorkflowInterface]
final class FastWorkflow
{
    #[\Temporal\Workflow\WorkflowMethod("wf")]
    public function run(string $name, int $count): \Generator
    {
        $activity = Workflow::newActivityStub(
            CommonActivity::class
        );

        $activity->slow($name)->then(function ($result) {
            $result['result'];
        });

        return 0;
    }
}
```

As I understand the problem is locating [here](https://github.com/temporalio/sdk-php/blob/master/src/DataConverter/JsonConverter.php#L86). But I don't know how to solve it.

**Comment by SerafimArts** [comment]
This is not a bug (More precisely, this is documented behavior). Please use DTO instead. 
Related issue https://github.com/temporalio/sdk-php/issues/93

**Comment by xepozz** [comment]
Then can you make behaviour more predictable:
if you return `['key' => 'test']` it will be converted to an object, but if you return `['test']` it will be converted to an array.

**Comment by SerafimArts** [comment]
> if you return ['key' => 'test'] it will be converted to an object, but if you return ['test'] it will be converted to an array.

Now that's how it works, isn't it?

**Comment by xepozz** [comment]
Yes, it is. But it isn't clear.
