### ISSUE TITLE
[Bug] Cannot decode value using Protobuf converter when fetching previous workflow result

### ISSUE THREAD

**Issue by benkelukas** [temporalio/sdk-php#141]
### What are you really trying to do?

When using CRON scheduled workflow and returning a protobuf message from said workflow, the message cannot be parsed when trying to fetch previous workflow result via `Workflow::getLastCompletionResult()`

### Describe the bug

1. Create a CRON scheduled workflow
2. Return a protobuf message from workflow as it's result
3. Fetch last completion result using `Workflow::getLastCompletionResult()`
4. There is an error:

```json
{
  "message": "Unable to decode value using protobuf converter - ",
  "source": "PHP_SDK",
  "stackTrace": "Temporal\\Exception\\DataConverterException: Unable to decode value using protobuf converter -  in /app/vendor/temporal/sdk/src/DataConverter/ProtoJsonConverter.php:50\nStack trace:\n#0 /app/vendor/temporal/sdk/src/DataConverter/DataConverter.php(53)... [omitted for brewity]
  "cause": null,
  "applicationFailureInfo": {
    "type": "Temporal\\Exception\\DataConverterException",
    "nonRetryable": false,
    "details": null
  },
  "failureInfo": "applicationFailureInfo"
}
```

### Minimal Reproduction

[https://github.com/benkelukas/samples-php/commit/620139f033bc68ae97db1b92bf65b6d4397c08d9](https://github.com/benkelukas/samples-php/commit/620139f033bc68ae97db1b92bf65b6d4397c08d9)

SimpleActivity is modified to use CRON schedules.

### Environment/Versions

- OS and processor: Intel MacOS, Catalina
- Temporal Version: 1.14.4, PHP SDK 1.1.1
- Docker setup

### Additional context

[Slack thread](https://temporalio.slack.com/archives/C01LK9FAMM0/p1643973542928279)

**Comment by seregazhuk** [comment]
@benkelukas I have investigated the problem. Try to do the following:
1. In your `WorkflowInterface` add explicit attribute for the return type:

```php
interface GreetingWorkflowInterface
{
    /**
     * @param string $name
     * @return WorkflowResult
     */
    #[WorkflowMethod(name: "SimpleActivity.greet")]
    #[ReturnType(WorkflowResult::class)]
    public function greet(
        string $name
    );
}
```
2. In the command don't forget that the result object is now `WorkflowResult`. Don't try to print it, and use on of the getters:
```php
$output->writeln(sprintf("Result:\n<info>%s</info>", $run->getResult()->getGreeting()));
```

Hope, it will help you. Waiting for you feedback.

**Comment by benkelukas** [comment]
Hi @seregazhuk 

thanks a lot for taking a look at this, it works! :)

I suppose I could've tried this by myself, however, there is the `ExpectedType` attribute on the `ReturnType` attribute's type argument, so I kinda supposed (wrongly) that this is not possible.

Maybe it would be also good to update docs to mention that one can, in fact, use PHP protobuf messages and what to do when one wants to use it for Workflow return types, as I think it's a pretty good way how to structure data passing between activities / worfklows - but I understand that not everybody wants to go through the hassle of generating PHP code from `.proto` files - not sure if it is in scope for the docs.

There remains one little caveat for me: PHPStorm complains that I've provided unexpected type to the `ReturnType` annotation, it's nothing serious and I can disable inspections for statement, but maybe the attribute could be expanded to allow custom types somehow?

Thanks again for taking the time to help me, You guys rock! :)

I'm closing the issue, cheers!
