### ISSUE TITLE
PHP docs reference wrong function or wrong class

### ISSUE THREAD

**Issue by the-invisible-man** [temporalio/sdk-php#158]
Much of what the template asked for was N/A.

There's the following doc section for `WorkerInterface::registerActivity()`:

https://github.com/temporalio/sdk-php/blob/d28e626710c07f5d5c3c3656a0a72308f89c8053/src/Worker/WorkerInterface.php#L70-L74

Let me bring your attention to line 74 which instructs the developer to use a callback function that accepts a `ReflectionClass` instance, and to call `getClass()` on the concrete object inside the callback. Where is `getClass()` coming from? The primitive PHP `ReflectionClass` doesn't have this method. Was `$class->getName()` the intended method, if one should be passing the fully qualified name of the class?

I searched the codebase to rule out whether the instance of `ReflectionClass` being passed is actually a child class that implements `getClass()` but couldn't find such implementation, and if I missed it, then perhaps the docs should suggest using the child class instead of `ReflectionClass` to avoid any issues with the IDE which currently complains that `getClass()` doesn't exist.
### Additional context
```
>>> $r = new \ReflectionClass(\App\User::class)
>>> $r->getClass()
PHP Error:  Call to undefined method ReflectionClass::getClass() in Psy Shell code on line 1
>>> $r->getName()
=> "App\User"
```

<img width="567" alt="Screen Shot 2022-04-14 at 2 39 18 PM" src="https://user-images.githubusercontent.com/5294918/163455495-cc0f8c92-69d4-46e6-ac71-2d2caa1e8434.png">

**Comment by seregazhuk** [comment]
Hi @the-invisible-man! Yes, you are absolutely right 👍 I have created a PR with a fix for - https://github.com/temporalio/sdk-php/pull/159

**Comment by the-invisible-man** [comment]
Thanks for the prompt fix @seregazhuk!

**Comment by seregazhuk** [comment]
Also, created a fix for official documentation - https://github.com/temporalio/documentation/pull/1055
