### ISSUE TITLE
[Bug] Workflow is always Running

### ISSUE THREAD

**Issue by OlegKuro** [temporalio/sdk-php#160]
### Workflow example to reproduce the bug:

```
class ExampleWorkflow implements ExampleWorkflowInterface {

    public function start(): string|\Generator
    {
        $promises = [];

        foreach (range(1, 20) as $i) {
            $promises[] = Workflow::async(function () use ($i) {
                yield Workflow::timer(random_int(5, 10));
                $this->completedIds[] = $i;
            });
        }

        Workflow::async(function () {
            yield Workflow::timer(30);
            $this->completedIds[] = 21;
            $this->continue = true;
        });

        Workflow::await(
            Promise::all($promises),
            fn () => $this->continue,
        );

        return 'FINISHED';
}
```
### Expected behavior:
After 10 seconds of execution the workflow stops since the first clause (`Promise::all` is resolved)
### Actual behavior:
The workflow never stops 😿

**Comment by OlegKuro** [comment]
I've also tried following workaround:
```
class ExampleWorkflow implements ExampleWorkflowInterface {

    public function start(): string|\Generator
    {
        $promises = [];

        foreach (range(1, 20) as $i) {
            $promises[] = Workflow::async(function () use ($i) {
                yield Workflow::timer(random_int(5, 10));
                $this->completedIds[] = $i;
            });
        }

        Workflow::async(function () {
            yield Workflow::timer(30);
            $this->completedIds[] = 21;
            $this->continue = true;
        });

        yield Promise::any([
            Promise::all($promises),
            Workflow::await(fn () => $this->continue),
        ]);

        return 'FINISHED';
}
```

It finishes the workflow. But only after `Workflow::await` clause resolution. But I expect to finish it after batch of promises completion.

I've tried many other identical expressions (like `Promise::await(Promise:all($promises));` instead of simple `Promise::all($promises);`), but nothing worked as I expected

What I am trying to implement is the opportunity to stop batch of promises execution (via external workflow signal). In non-minimalist real code example these promises are allowed to never resolve at all.

**Comment by seregazhuk** [comment]
Hi @OlegKuro! I think the problem is - missing `yield`s here. With `Workflow::await()` and `Workflow::await()` you just create promises. To actually execute the code inside you need to call `yield`. So, your first workflow can be rewritten this way:

```php
final class ExampleWorkflow
{
    private array $completedIds = [];
    private bool $continue = false;

    #[WorkflowMethod]
    public function handle()
    {
        $promises = [];

        foreach (range(1, 20) as $i) {
            $promises[] = Workflow::async(function () use ($i) {
                yield Workflow::timer(1);
                $this->completedIds[] = $i;
            });
        }

        yield Workflow::async(function () {
            yield Workflow::timer(30);
            $this->completedIds[] = 21;
            $this->continue = true;
        });

        yield Workflow::await(
            Promise::all($promises),
            fn () => $this->continue,
        );

        return 'FINISHED';
    }
}
```

**Comment by OlegKuro** [comment]
Thank you for your reply! 🤗 

Indeed! It works if I use `yield` correctly. But it resolves after both Promise and Closure completion. What if I need to create a bunch of interruptable actions? 🤔 
Is there any way to implement following `main` function example using temporal capabilities?

<details>
<summary>JavaScript identical to what I am trying to implement snippet</summary>
You can merely paste it into a browser console and run `runAndThenInterrupt` and `runAndWaitForPromises` functions 

```
let doContinue = false;
    
function sleep(ms) {
    return new Promise(resolve => {
        setTimeout(() => resolve(), ms)
    })
}

function sleepAndLog(ms, id) {
    return sleep(ms).then(() => {
        console.log(`${id} completed!`);
    })
}

async function main(interruptor) {
    async function interruptor() {
        return new Promise(resolve => {
            let intervalId = setInterval(() => {
                if (doContinue) {
                    doContinue = false;
                    console.log('interruption signal received!');
                    clearInterval(intervalId);
                    resolve();
                }
            }, 0);
        })
    }
    promises = [sleepAndLog(1000, 1), sleepAndLog(500, 2), sleepAndLog(1500, 3)];

    await Promise.any([
        Promise.all(promises),
        interruptor(),
    ]);

    console.log('promise any resolved!');
}

async function runAndThenInterrupt() {
    main();
    await sleep(700);
    doContinue = true;
}

function runAndWaitForPromises() {
    main();
}
```

</details>

Why [this](https://github.com/temporalio/sdk-php/issues/160#issuecomment-1099714010) example does not work as expected? 😵

**Comment by seregazhuk** [comment]
In your last example you have a missing `yield` keyword before the second `Workflow::async`:

```php
yield Workflow::async(function () {
    yield Workflow::timer(30);
    $this->completedIds[] = 21;
    $this->continue = true;
});

yield Promise::any([
   Promise::all($promises),
   Workflow::await(fn () => $this->continue),
]);
```

**Comment by OlegKuro** [comment]
Btw, I do not see `yield` before `Workflow::async` in [example](https://docs.temporal.io/docs/php/workflows#awaits) from documentation. Is it official way of using `Workflow::async` 🤔 ? 

Coluld you please explain why sometimes `Workflow::async` works without `yield` before it? 
For example, If I create array of promises with help of `Workflow::async` and then wait for their resolution via` Promise::all `method, it works 🤯
