### ISSUE TITLE
[Bug] Parent workflow waits for child completion

### ISSUE THREAD

**Issue by OlegKuro** [temporalio/sdk-php#165]
### What are you really trying to do?

I'm trying to divide one process into two workflows: the first one starts the process and then spawns the second one (child workflow) and immediately completes. Then the second workflows works, but the first should be completed.

### Describe the bug

Instead of spawning and immediate completion parent workflow waits for child workflow resolution.
I've tried to find any documentation about correct behavior in this case and found [golang temporal notes](https://docs.temporal.io/docs/go/how-to-spawn-a-child-workflow-execution-in-go/#asynchronous-execution):

> To asynchronously spawn a Child Workflow Execution, the Child Workflow must have an "Abandon" Parent Close Policy set in the Child Workflow Options. Additionally, the Parent Workflow Execution must wait for the "ChildWorkflowExecutionStarted" event to appear in its event history before it completes.

> If the Parent makes the ExecuteChildWorkflow call and then immediately completes, the Child Workflow Execution will not spawn.

Does it mean that parent workflow should not wait? 🤔 

### Minimal Reproduction

```
class ExampleWorkflow {

    public function run()
    {
        $child = Workflow::newChildWorkflowStub(
            ChildWorkflowExampleInterface::class,
            ChildWorkflowOptions::new()
                ->withWorkflowId(bin2hex(random_bytes(18)))
                ->withWorkflowIdReusePolicy(WorkflowIdReusePolicy::WORKFLOW_ID_REUSE_POLICY_ALLOW_DUPLICATE)
                ->withParentClosePolicy(ParentClosePolicy::POLICY_ABANDON)
        );
        $child->run();

        return 'COMPLETED';
    }
}
```

### Environment/Versions

- Temporal SDK Version: 1.1.1

### Additional context

Workflow also waits for activities completion too... I mean I can start an activity and then do some stuff in workflow body. But it seems to not finish while spawned in this workflow activities won't complete. Is it ok?

**Comment by seregazhuk** [comment]
@OlegKuro thank you! Yes, we have a bug here. Will be fixed in #167 💪

**Comment by OlegKuro** [comment]
@seregazhuk thank you for fix! 🙏 ❤️ 

But I think I had created too many issues (sorry 😅) so you confused #166 and this issue (#165)

> @OlegKuro the parent should wait for its child. Using abandon policy means that once parent is canceled/terminated the child continues working.
> Related docs:
> 
> [Policy](https://docs.temporal.io/docs/concepts/what-is-a-parent-close-policy/)
> [Execution concepts](https://docs.temporal.io/docs/concepts/what-is-a-child-workflow-execution/)

Thank you, got it 🤔 . 
But I can create an activity capable of running another workflow via workflow client injected into it. 
Would it be more convenient legalizing this hack? 

For example,
I accumulate requests by `sourceId` in the parent workflow. When I get a certain condition matched, I start another workflow which processes accumulated data and finish execution of parent workflow since this condition is matched until I get a new request with this `sourceId`. 
Parent workflow id is `sourceId`. Child workflow id is `sourceId-processingStartedAt`. 
In this case I need an opportunity to spawn another workflow and then finish parent workflow execution (or even better to perform these actions simultaneously)

**Comment by seregazhuk** [comment]
@OlegKuro if it is still relevant to you... your code from this issue should work now 👍  Please, try to update to the latest SDK version. The parent only waits for child to start. Once the child is started, the parent (with abandon policy) can be completed.
