### ISSUE TITLE
[Bug] Workflow timer debouncing does not work

### ISSUE THREAD

**Issue by OlegKuro** [temporalio/sdk-php#166]
### What are you really trying to do?

I'm trying to write [debonce](https://lodash.com/docs/4.17.15#debounce) workflow equivalent: workflow should start and then wait for the signal **N** seconds. And then if signal is triggered within these **N** seconds, timer should be re-launched. If the signal is not triggered workflow should go further. 

### Describe the bug

It seems to not work at all. Workflow jams in _Running_ state instead of timer cancellation and then resetting another one. Also roadrunner writes this message:
<details>
<summary> Long golang-ish error from roadrunner container </summary>

```
roadrunner_1            | 2022-04-27T12:17:28.779Z      ERROR   temporal        Workflow panic  {"Namespace": "default", "TaskQueue": "default", "WorkerID": "default:e6ab0423-3304-4edf-a4d9-ef3f2af0d391", "WorkflowType": "ExampleWorkflow", "WorkflowID": "some_id", "RunID": "0d757f3f-5c7c-4b80-bcb0-1ade96fc82cc", "Attempt": 48, "Error": "flush queue: SoftJobError:\n\tcodec_execute:\n\tsync_worker_exec:\n\tsync_worker_exec_payload: LogicException: Got the response to undefined request 9002 in /opt/app/vendor/temporal/sdk/src/Internal/Transport/Client.php:60\nStack trace:\n#0 /opt/app/vendor/temporal/sdk/src/WorkerFactory.php(389): Temporal\\Internal\\Transport\\Client->dispatch(Object(Temporal\\Worker\\Transport\\Command\\SuccessResponse))\n#1 /opt/app/vendor/temporal/sdk/src/WorkerFactory.php(261): Temporal\\WorkerFactory->dispatch('\\n\\x03\\x08\\xAAF\\n\\x03\\x08\\xABF', Array)\n#2 /opt/app/bin/worker(45): Temporal\\WorkerFactory->run()\n#3 {main}", "StackTrace": "process event for default [panic]:\ngithub.com/temporalio/roadrunner-temporal/workflow.(*process).OnWorkflowTaskStarted(0xc000d7fa40, 0xc001734ec8)\n\tgithub.com/temporalio/roadrunner-temporal@v1.1.0/workflow/workflow.go:144 +0x2e5\ngithub.com/spiral/sdk-go/internal.(*workflowExecutionEventHandlerImpl).ProcessEvent(0xc000934330, 0xc000abb940, 0xc0, 0x1)\n\tgithub.com/spiral/sdk-go@v1.12.0/internal/internal_event_handlers.go:801 +0x1ff\ngithub.com/spiral/sdk-go/internal.(*workflowExecutionContextImpl).ProcessWorkflowTask(0xc00027b490, 0xc001666630)\n\tgithub.com/spiral/sdk-go@v1.12.0/internal/internal_task_handlers.go:874 +0xca8\ngithub.com/spiral/sdk-go/internal.(*workflowTaskHandlerImpl).ProcessWorkflowTask(0xc000294210, 0xc001666630, 0xc001578ea0)\n\tgithub.com/spiral/sdk-go@v1.12.0/internal/internal_task_handlers.go:723 +0x493\ngithub.com/spiral/sdk-go/internal.(*workflowTaskPoller).processWorkflowTask(0xc000a8add0, 0xc001666630)\n\tgithub.com/spiral/sdk-go@v1.12.0/internal/internal_task_pollers.go:284 +0x2cd\ngithub.com/spiral/sdk-go/internal.(*workflowTaskPoller).ProcessTask(0xc000a8add0, {0x1594180, 0xc001666630})\n\tgithub.com/spiral/sdk-go@v1.12.0/internal/internal_task_pollers.go:255 +0x6c\ngithub.com/spiral/sdk-go/internal.(*baseWorker).processTask(0xc0005f2200, {0x1593d40, 0xc001807160})\n\tgithub.com/spiral/sdk-go@v1.12.0/internal/internal_worker_base.go:362 +0x167\ncreated by github.com/spiral/sdk-go/internal.(*baseWorker).runTaskDispatcher\n\tgithub.com/spiral/sdk-go@v1.12.0/internal/internal_worker_base.go:282 +0xba"}
```

</details>

### Minimal Reproduction

```php
class ExampleWorkflow {
    private bool $stopWaiting = false;

    public function run()
    {
        while (!$this->stopWaiting) {
            $this->stopWaiting = true;

            yield Workflow::awaitWithTimeout(
                30,
                fn () => $this->stopWaiting === false
            );
        }

        return 'COMPLETED';
    }

    // signal
    public function resetTimer(): void
    {
        $this->stopWaiting = false;
    }
}
```

Try to trigger the signal several times a second -- this will reproduce the bug for sure 😄 

### Environment/Versions

- Temporal SDK Version: 1.1.1

### Additional context

I've implemented this logic another way. But I'm still wondering why this implementation did not work 🤯

**Comment by OlegKuro** [comment]
I've just tried to use [proposed updatable timer implementation](https://github.com/temporalio/samples-php/blob/master/app/src/UpdatableTimer/UpdatableTimer.php). And it does not work 😭 

These issues are related to attempt to re-launch `awaitWithTimeout` method I guess 🥲 
Because I've tried to implement updatable timer logic via simple `Workflow::timer` method (_Instead of termination and fair re-launching the timer I wrote new awakeTime into variable and looked on it after each awakening_) and it worked. 

_Temporal version: 1.13.3
Temporal php-SDK version: 1.1.1_

**Comment by wolfy-j** [comment]
That is weird. We will check the behaviour.

**Comment by seregazhuk** [comment]
@OlegKuro the parent **should wait** for its child. Using abandon policy means that once parent is canceled/terminated the child continues working.
Related docs:
- [Policy](https://docs.temporal.io/docs/concepts/what-is-a-parent-close-policy/)
- [Execution concepts](https://docs.temporal.io/docs/concepts/what-is-a-child-workflow-execution/)
