### ISSUE TITLE
Process execution does not continue after await condition is satissfied (through signals)

### ISSUE THREAD

**Issue by jcontesse** [temporalio/sdk-php#174]
I am trying to halt process execution until one of two condition are met.
These conditions are set by two distinct signals.

In general, everything works fine but in some cases (and it is often... maybe 10% of the cases), the signal is received and processed but the instance does not continue its execution. I have not been able to identify a pattern.

So I am waiting for the conditions like this:

`yield Workflow::await(fn() => !is_null($this->authorizationId) || $this->exitProcess);`

Waiting to execute one of these signals:

```
    public function workflowAuthorizationExecuted(int $taskId)
	{
		$this->authorizationId = $taskId;
	}

    public function indicationHasBeenSuspended()
	{
		$this->exitProcess = true;
	}
```
Maybe I am doing something wrong, but I find it strange that some instances work and some don't.
For those instances that don't work, even if I resend the signal nothing happens.
How can I make sure the instance is waiting in the "await" command?

I haven't been able to replicate in our DEV or QA environment. It is happening in production.
I have attached my workflow definition.

I am using docker under Alpine Linux v3.11.
- RR_VERSION: 2.8.4
- PHP_IMAGE_VERSION: 8.1.4-cli
- mysql:8
- temporalio/auto-setup:1.15.0
[AutorizarIndicacionWorkflow.php.txt](https://github.com/temporalio/sdk-php/files/8758303/AutorizarIndicacionWorkflow.php.txt)

**Comment by jcontesse** [comment]
This is my SDK version
```
{
    "require": {
        "spiral/roadrunner": "^2.8",
        "temporal/sdk": "^1.1",
        "nyholm/psr7": "^1.5"
    }
}
```

I see issue #170 has some similarities. I am not sure if this happens after a worker crashes.

**Comment by seregazhuk** [comment]
@jcontesse can you try the latest SDK version? We have recently fixed similar issues with awaits and signals.

**Comment by jcontesse** [comment]
So I am now using the following versions:

- PHP_IMAGE_VERSION: 8.1.4-cli
- mysql:8
- temporalio/auto-setup:1.15.0
- "spiral/roadrunner": "^2.10.1",
- "temporal/sdk": "^1.3",
- "nyholm/psr7": "^1.5"

I ran the process for almost a week and today the same thing happened. A couple of processes hanged after the signal was received with no apparent explnation.

It seems this started happening after one of the workers failed (not sure what happened). I have attached that instance's execution log.

Should I update temporal?
What other information can I gert in order to be more helpful?

[Worker Error.txt](https://github.com/temporalio/sdk-php/files/8800946/Worker.Error.txt)
.

**Comment by seregazhuk** [comment]
@jcontesse please try to update RR to `v2.10.3` and sdk to `v1.3.2`. Hope, it will help you.

**Comment by jcontesse** [comment]
It has been nearly one week running RR v2.10.3 and sdk v1.3.2 with no issues. It seems the issue has been fixed. We are still monitoring.

**Comment by seregazhuk** [comment]
Great news! 🚀
