### ISSUE TITLE
[Question] Kubernetes pod scaling

### ISSUE THREAD

**Issue by dmitry-pilipenko** [temporalio/sdk-php#178]
I did not find in the documentation how to properly scale pods with workers in kubernetes.
I want to scale workers in several different AWS zones. But the road runner has an internal process orchestration and is not suitable for such purposes.
Is it possible to scale pods? And will this cause a problem?

**Comment by rustatian** [comment]
Hey @dmitry-pilipenko 👋🏻. 
> But the road runner has an internal process orchestration and is not suitable for such purposes.

RoadRunner works fine for such type of scaling. It's just an application, it doesn't scale (up or down) the PHP processes, and they are constant. Having this in mind, you may easily scale your pods with the RR inside.
You may use temporal and/or RR metrics to scale your cluster. For example: `queue_size` which indicates how many requests are waiting for the worker, or temporal metrics: https://docs.temporal.io/operation/how-to-tune-workers/

**Comment by dmitry-pilipenko** [comment]
@rustatian thank you!
