### ISSUE TITLE
[Bug] Abandoned child workflow don't release flow

### ISSUE THREAD

**Issue by koekaverna** [temporalio/sdk-php#184]
### What are you really trying to do?
I made repo with example https://github.com/koekaverna/samples-php/tree/background-child/app/src/ChildBackground

### Describe the bug
I expect that parent workflow return result imidiately when there is no `yield` on child workflow. It does not. It was waiting for child process done and had timeout exception.

### Minimal Reproduction
Look at the repo

### Environment/Versions

- I am using docker-compose from source

**Comment by seregazhuk** [comment]
Hi @koekaverna! The parent workflow always waits till the child workflow is finished.
Related docs:

[Policy](https://docs.temporal.io/docs/concepts/what-is-a-parent-close-policy/)
[Execution concepts](https://docs.temporal.io/docs/concepts/what-is-a-child-workflow-execution/)

**Comment by koekaverna** [comment]
> Hi @koekaverna! The parent workflow always waits till the child workflow is finished. Related docs:
> 
> [Policy](https://docs.temporal.io/docs/concepts/what-is-a-parent-close-policy/)  
[Execution concepts](https://docs.temporal.io/docs/concepts/what-is-a-child-workflow-execution/)

> A Parent Workflow Execution must await on the Child Workflow Execution to spawn. The Parent can **optionally** await on the result of the Child Workflow Execution.

![image](https://user-images.githubusercontent.com/20415858/173043142-d21051b6-9729-4d2a-acf9-979f2d128bac.png)

It seems parent workflow should not await child workflow. After child workflow starts it is optional to wait results.
@seregazhuk

**Comment by seregazhuk** [comment]
Oh, sorry.

**Comment by koekaverna** [comment]
> Try to remove your exception throwing.
It does not solve the problem. Why parent workflow waits child, when no result is awaited with yield?

I have this scenario:
1. Send the request1 to the server1 using workflow.
2. Waiting it for the _response_.
3. Log the _response_ using another request2 to a logging server2
4. Return result of the _response_

In this case server2 can be anavailabale for sometime and I want to retry request2 until it will be done.
I need return result of request1 imideately after I get response from server1.
I do not need to wait the result of request2 in the worklow.

Is it possible somehow to do this?

@seregazhuk

**Comment by seregazhuk** [comment]
Yes, there is an issue with parent/child workflows 😞 we are working on it. As a quick solution I can see - separate it to two different workflows.

**Comment by koekaverna** [comment]
Wow it's amazing 🎉
