### ISSUE TITLE
[Feature Request] Add API reference

### ISSUE THREAD

**Issue by lorensr** [temporalio/sdk-php#213]
I see the docs at https://docs.temporal.io/php/introduction/ but is there a structured list of functions etc that the package provides?

**Comment by rustatian** [comment]
Hey @lorensr 👋🏻 
Is this still actual? As far as I understand, there is no such docs for other SDKs, am I right?

**Comment by rustatian** [comment]
I think, for the PHP should be used phpdoc: https://www.phpdoc.org/

**Comment by lorensr** [comment]
If you add a step to CI that uses phpdoc to generate html, I can add a step
that publishes it to php.temporal.io

**Comment by josh-berry** [comment]
@wolfy-j We'll soon have things set up for you to start publishing API docs once you're ready. To publish from CI, you just need to generate the docs and then:

```
npx vercel deploy path/to/generated/docs -t ${{ secrets.VERCEL_TOKEN }} --name php --scope temporal --prod --yes
```

(The token's already set in the repo secrets.)

Our IT folks just need to finish up a couple things to get the domain ready (hopefully will be done by the time you read this).

**Comment by roxblnfk** [comment]
> Looks like we can close this? https://php.temporal.io/

Waiting merging https://github.com/temporalio/sdk-php/pull/408
The issue will be closed automatically
