### ISSUE TITLE
Expose Replayer API

### ISSUE THREAD

**Issue by bergundy** [temporalio/sdk-php#227]
See other SDKs for reference.
Go SDK already provides this functionality, need to wrap the API and expose to PHP.
The purpose of the replayer is:
- replay workflow histories against new workflow code to check for non-determinism
- replay workflow history from a production workflow and debug locally

**Comment by michael-rubel** [comment]
@seregazhuk how it's going with implementing the Replay feature?

We can't wait to test it in PHP. 😉
