### ISSUE TITLE
[CHORE] Remove deprecated structure fields

### ISSUE THREAD

**Issue by rustatian** [temporalio/sdk-php#253]
### Is your feature request related to a problem? Please describe.

ref: https://github.com/temporalio/roadrunner-temporal/pull/278

### Describe the solution you'd like

Remove deprecated `WorkflowExecutionTimeout` field from the `ContinueAsNew` request

**Comment by roxblnfk** [comment]
@rustatian should I delete [that](https://github.com/temporalio/sdk-php/blob/0863b6118d280bb46d68031b9b1b2e5f40df807d/src/Workflow/ContinueAsNewOptions.php#L47-L53)?
Will it affect somethink?

**Comment by rustatian** [comment]
@roxblnfk You're pointing to a `WorkflowTaskTimeout`, but the deprecated field is `WorkflowExecutionTimeout`. I dunno where it is in the PHP code. I guess, that somewhere in the `ContinueAsNew` command and the `WorkflowExecutionTimeout` should be somewhere in it.

**Comment by roxblnfk** [comment]
> @roxblnfk You're pointing to a `WorkflowTaskTimeout`, but the deprecated field is `WorkflowExecutionTimeout`. I dunno where it is in the PHP code. I guess, that somewhere in the `ContinueAsNew` command and the `WorkflowExecutionTimeout` should be somewhere in it.

Oh. Yes. Then it looks OK and I just need to remove `WorkflowExecutionTimeout` from [there](https://github.com/temporalio/sdk-php/blob/0863b6118d280bb46d68031b9b1b2e5f40df807d/src/Workflow/ContinueAsNewOptions.php#L30-L33)
