### ISSUE TITLE
[Bug] PHP 8 named arguments don't work

### ISSUE THREAD

**Issue by roxblnfk** [temporalio/sdk-php#272]
### What are you really trying to do?

I am trying to call workflow handler using PHP8 named arguments.

```php
// Workflow handker signature:
public function handler(bool $foo = false, bool $bar = false): iterable;

// Calling
$workflowStub->handler(bar: true);
```
In this case the handler will be started with `[true, false]` values

### Environment/Versions

PHP 8.1, SDK-PHP 2.3.2

**Comment by wolfy-j** [comment]
Named arguments are not allowed due to limited language support.

**Comment by roxblnfk** [comment]
> Named arguments are not allowed due to limited language support.

In the SDK-PHP we support PHP syntax. When named arguments are used we will send all skipped default values:

```php
// activity method
public function doSomething(?int $number = 0, string $foo = 'default', ?Bar $bar = null);
```

If we call `doSomething(foo: 'custom');` values `[0, 'custom']` will be sent (without names of course)

**Comment by wolfy-j** [comment]
Ah... ok, so it's on packing side.
