### ISSUE TITLE
[Feature Request] Do not require server CA cert in client createSSL

### ISSUE THREAD

**Issue by cretz** [temporalio/sdk-php#286]
### Is your feature request related to a problem? Please describe.

Most production servers, including our cloud, don't need to override the CA as its either signed by a known CA or they install the CA root at the system level. Client cert and key are the most important.

Like https://grpc.github.io/grpc/php/class_grpc_1_1_channel_credentials.html#a21a46268a69dcc263360c63193b89955 we should accept null.

**Comment by rustatian** [comment]
@cretz Friendly ping. Please add more details to this ticket? Would be super helpful if you could attach the links to the PHP SDK src.
