### ISSUE TITLE
Add API to count workflows

### ISSUE THREAD

**Issue by bergundy** [temporalio/sdk-php#291]
See parent issue for more information

**Comment by wolfy-j** [comment]
@roxblnfk i believe this feature available via listWorkflowExecutions Paginator.

**Comment by roxblnfk** [comment]
> @roxblnfk i believe this feature available via listWorkflowExecutions Paginator.

Yes it is

**Comment by cretz** [comment]
The paginator isn't good enough I don't think, this is a separate `CountWorkflowExecutions` API call. Also, be prepared due to https://github.com/temporalio/api/pull/303 to support more than just integer response.

**Comment by wolfy-j** [comment]
In that case it makes sense to expose it as separate endpoint. @roxblnfk

**Comment by roxblnfk** [comment]
Should I remove `countable` from the paginator with adding that separated API point?
