### ISSUE TITLE
Is this SDK available in standalone without RoadRunner ?

### ISSUE THREAD

**Issue by lerminou** [temporalio/sdk-php#3]
Hi,

I tried to clone the SDK in my project but I got a question.
I already have a stack in my company for PHP and I want to include Temooral server instead of RabbitMQ.
I want to directy send workflow or receive activities from PHP.

I know it's just the beginning of the SDK, but before to try some use-cases, I want to know if it will be compatible.

The example emulator works well, but when I tried to change the client endpoint to 'temporal:7233' (the available temporal server endpoint).
I got the following error:

I used the default docker-compose from temporal 1.0.0-rc1

```
Temporal.ERROR: Spiral\Goridge\Exception\ProtocolException: Can not read input stream, chunk must a type of string, but bool given in /var/www/directory/vendor/spiral/goridge/src/Protocol/Protocol.php:104 
Stack trace: #0 /var/www/directory/vendor/spiral/goridge/src/Protocol/Protocol.php(79): Spiral\Goridge\Protocol\Protocol->errorChunkType(false) 
#1 /var/www/directory/vendor/spiral/goridge/src/Protocol/Protocol.php(59): Spiral\Goridge\Protocol\Protocol->stream(2, Object(Closure)) 
#2 /var/www/directory/vendor/spiral/goridge/src/Protocol/Version1/Decoder.php(38): Spiral\Goridge\Protocol\Protocol->streamToString(17) 
#3 [internal function]: Spiral\Goridge\Protocol\Version1\Decoder->decode(Object(Spiral\Goridge\Protocol\Stream\Factory)) 
#4 /var/www/directory/vendor/spiral/goridge/src/Transport/Receiver/ResourceStreamReceiverTrait.php(40): Generator->send(false) 
#5 /var/www/directory/vendor/spiral/goridge/src/Transport/ReactReceiver.php(39): Spiral\Goridge\Transport\StreamReceiver->push(Object(Spiral\Goridge\Protocol\Stream\Factory), Object(Spiral\Goridge\Protocol), Resource id #56) 
#6 /var/www/directory/vendor/react/event-loop/src/StreamSelectLoop.php(245): Spiral\Goridge\Transport\ReactReceiver->Spiral\Goridge\Transport\{closure}(Resource id #56) 
#7 /var/www/directory/vendor/react/event-loop/src/StreamSelectLoop.php(212): React\EventLoop\StreamSelectLoop->waitForStreamActivity(NULL) 
#8 /var/www/directory/vendor/archemed/common-symfony/Worker.php(213): React\EventLoop\StreamSelectLoop->run() 
#9 /var/www/directory/vendor/archemed/common-symfony/RestartableExecutor.php(105): Temporal\Client\Worker->run('default') 
#10 /var/www/directory/public/client.php(45): Temporal\Client\RestartableExecutor->run() #11 {main} [] []
```

**Comment by wolfy-j** [comment]
Hi, this SDK is currently in active development and won't work without the Golang coordinator on RoadRunner.

Once the implementation complete we will take a look at providing access to Temporal functions using native PHP SDK, however, the native client will only be capable of handling general API calls (i.e. StartWorkflow) and activity execution (using a blocking loop). 

The development of a workflow runner on PHP without the Golang coordinator is a challenging task and currently not on our roadmap. Since workflows state machines are generally well isolated from the rest of the codebase you should be capable of embedding RoadRunner to your application without affecting the rest of the code.

**Comment by lerminou** [comment]
OK i thought this SDK was in charge to handle RPC calls to Temporal with the proto interfaces or FFI to the go SDK, but it's more like a roadrunner plugin right ?
I don't have experiences with roadrunner, I will take a look, if it's easy to integrate

**Comment by wolfy-j** [comment]
This SDK currently focuses on base primitives to handle workflow executions on PHP. It will operate as a standalone server as well as a RoadRunner plugin. RPC calls to Temporal will be included as well, but the scope of this function is much smaller than what we are trying to do. 

You can check the original proposal here: https://github.com/temporalio/proposals/blob/master/php/php-rr-sdk.md

**Comment by sagikazarmark** [comment]
While I like and generally agree with the approach, I think it would be a quick win to support launching new workflows from a PHP application without support for actually implementing workers in PHP.

I think a lot of users have polyglot applications where the primary API is implemented in PHP and some internal services are implemented in nodejs, python, Go, etc.

I haven't looked at the current SDK closely, so I don't know if this is already implemented, but I think it's a low-hanging fruit that would be worth prioritizing.

**Comment by wolfy-j** [comment]
> I think it would be a quick win to support launching new workflows from a PHP application without support for actually implementing workers in PHP.

We are not planning to handle GRPC endpoints in this SDK but we do provide RoadRunner native RPC. Please sit tight, we are entering into assembly part of this SDK, I hope to provide working Aplha very soon.

**Comment by wolfy-j** [comment]
Update: a recent version of WorkflowService uses GRPC and does not require RoadRunner to work, you can launch workflows from legacy codebases. Activities and workflows will require a supervior.

**Comment by lerminou** [comment]
Hi. Thanks for the update. 
For now I'm using the temporal proto compiled to php too.
I released a composer package to perform the same work. You're free to use it if you want. https://github.com/lerminou/temporal-api

**Comment by wolfy-j** [comment]
Hi,

we are using additional (generated) mapping at top of the default GRPC client to improve it's usability. Our additions:
1) Java-like Workflow and Activity clients
2) Retries and Timeouts
3) Isolated and typed interface for the service client instead of native `GRPC->wait()[0]`
