### ISSUE TITLE
[Bug] Activity not scheduled in signal handler

### ISSUE THREAD

**Issue by antmendoza** [temporalio/sdk-php#314]
### What are you really trying to do?

Schedule/invoke an activity in a signal handler

### Describe the bug

Having the following workflow code, where addName is a  `#[SignalMethod]`,
```php

    public function addName(string $name): void
    {
        $this->greetingActivity->composeGreeting('Hello', $name);
    }

```

One customer reported that sometimes the activity is not scheduled after the signal is delivered to the workflow execution.  
It does not make any difference if the activity invocation sync or async 

I have tried to reproduce the issue with no luck. 

Attaching two event histories following this same path. As can be noted, in one of them the activity is not scheduled after receiving the signal (event 15), which later causes an NDE on replay. 

![event-history-revised](https://github.com/temporalio/sdk-php/assets/514932/6cb34aa0-5509-4544-9fe7-6bc9f99fa49c)

![event-history-revised-2](https://github.com/temporalio/sdk-php/assets/514932/b60dbaa5-9586-43eb-ba03-f447a75766db)

### Environment/Versions

- OS and processor: [e.g. M1 Mac, x86 Windows, Linux]
- Temporal Version: [e.g. 1.14.0?] and/or SDK version
- Are you using Docker or Kubernetes or building Temporal from source?

**Comment by antmendoza** [comment]
The customer sees this pattern in 0,75% of the workflow executions.

**Comment by wolfy-j** [comment]
Are there any details on the behavior of the primary workflow method? Does it spawn any coroutines, what is the exit condition?

**Comment by dbakiu** [comment]
Hello, thanks for looking into it. 

The main workflow sets several class properties, it invokes several activities (database updates, API calls to other services), and ultimately waits for a timer to expire. Once the timer expires, it continues to invoke a few more activities, after which it terminates. 

Please feel free to ping me for any other questions.

**Comment by wolfy-j** [comment]
Can you provide us with some simplistic way to represent your workflow? When your timer fires and you exit - do you wait for schedules activities in signals to be completed?

**Comment by dbakiu** [comment]
Hi Anton, here's a high level description of what the workflow does:
- sets several properties of the class based on an argument that gets passed to the workflow method
- executes `activityAlpha` (database call)
- fetches the version of the workflow, and depending on that, performs `activityBeta` (API call via HTTP) or skips it
- in a for cycle, it sleeps for a specific amount of days and upon wakeup it executes `activityGamma` (API call via HTTP), and, depending on the version again, invokes `activityBeta` (API call via HTTP) for a maximum of 3 times
- once out of the cycle, depending on the version, it sleeps for several days and performs `activityBeta` (API call via HTTP), or skips it entirely
- waits for another timer which sleeps for several days
- upon wakeup, it executes 4 different activities (similarly to the ones above, 3 API calls via HTTP  and 1 database call)
- it terminates

We're yield-ing all invocations of the activities/promises, both inside the workflow, as well as the signal. I assume this is considered as "waiting" for the activities to be completed. If not, then could you please clarify what you mean exactly?

Thanks,
Driton

**Comment by roxblnfk** [comment]
@dbakium like this?

```php

class TestWorkflow
{
    private mixed $arg1;
    private mixed $arg2;
    private ActivityProxy $activityAlpha;
    private ActivityProxy $activityBeta;
    private ActivityProxy $activityGamma;

    public function handler(mixed $arg1, mixed $arg2)
    {
        $this->arg1 = $arg1;
        $this->arg2 = $arg2;

        yield $this->activityAlpha->execute();
        /*if version...*/ yield $this->activityBeta->execute();

        $result = [];
        for ($i = 3; $i > 0; $i--) {
            yield Workflow::timer('5 days');

            yield $this->activityGamma->execute();
            /*if version...*/ yield $this->activityBeta->execute();
        }
        yield Workflow::timer('5 days');

        /*if version...*/ yield $this->activityBeta->execute();
    }

    public function signal(string $arg)
    {
        yield $this->activityBeta->execute($arg);
    }
}
```

**Comment by dbakiu** [comment]
Hi Aleksei, 

Yes, the only difference is that the invoked signal contains several class property assignments as well, so something like:
` 
    public function signalAlpha(bool $newStatus)
    {
      $this->arg1 = $newStatus;
        yield $this->activityAlpha->execute(new DatabaseUpdateRequest($newStatus));
    }

`

**Comment by roxblnfk** [comment]
In your case the workflow may be closed before an activity from a signal method will be done

Some signal method activity counter might help:

```php
class Test
{
    private mixed $arg1;
    private mixed $arg2;
    private ActivityProxy $activityAlpha;
    private ActivityProxy $activityBeta;
    private ActivityProxy $activityGamma;
    // FIX: Add signals counter
    private ActivityProxy $waitingSignals;

    public function handler(mixed $arg1, mixed $arg2)
    {
        $this->arg1 = $arg1;
        $this->arg2 = $arg2;

        yield $this->activityAlpha->execute();
        /*if version...*/ yield $this->activityBeta->execute();

        $result = [];
        for ($i = 3; $i > 0; $i--) {
            yield Workflow::timer('5 days');

            yield $this->activityGamma->execute();
            /*if version...*/ yield $this->activityBeta->execute();
        }
        yield Workflow::timer('5 days');

        /*if version...*/ yield $this->activityBeta->execute();

        // FIX: Wait signals completion
        /* if yet another version... */ yield Workflow::await(fn() => $this->waitingSignals === 0);
    }

    public function signalAlpha(string $arg)
    {
        // FIX
        ++$this->waitingSignals;
        try {
            yield $this->activityAlpha->execute($arg);
        } finally {
            --$this->waitingSignals;
        }
    }

    public function signalBeta(string $arg)
    {
        // FIX
        ++$this->waitingSignals;
        try {
            yield $this->activityBeta->execute($arg);
        } finally {
            --$this->waitingSignals;
        }
    }

    public function signalGamma(string $arg)
    {
        // FIX
        ++$this->waitingSignals;
        try {
            yield $this->activityGamma->execute($arg);
        } finally {
            --$this->waitingSignals;
        }
    }
}
```

**Comment by dbakiu** [comment]
I'm not sure that's the issue here, as the workflows in question whose signals failed to schedule the activity were/are still running, so it's not that the workflows terminated before the activity included in the signal could execute. However, that is a good suggestion and it's something we'll take a look at moving further.

**Comment by roxblnfk** [comment]
@dbakiu do I understand correctly that versioning rules have always been followed in your code and the appearance of the activity call in the signal method on the second image cannot in any way be connected with such a possibility that in some previous revision of this activity launch code there was no?

**Comment by dbakiu** [comment]
@roxblnfk definitely, the signal itself hasn't changed since the initial version of the workflow was deployed, so no versioning rule exist within the signal definition.

**Comment by wolfy-j** [comment]
You got it. Can you also tell us which Temporal SDK version you use? We are working on reproducing this use-case...

**Comment by dbakiu** [comment]
Hi, thanks for the update.
We're using `v2.5.0`, on an Alpine-based docker image, on Kubernetes.

**Comment by roxblnfk** [comment]
@dbakiu could you tell RR version and PHP?

**Comment by rustatian** [comment]
Hey @dbakiu 👋🏻 
Could you please check, what RR version you use? `./rr --version` command output.

**Comment by rustatian** [comment]
Also, if that's possible, could you please provide debug (would be super cool) or at least error logs before/after this happens?

We tried to reproduce the bug, no luck. Sending hundreds of signals to the dozens of workflows - no luck. I think that these failures happened because of the WF worker restarts due to out of memory or some other exception.

**Comment by dbakiu** [comment]
> Hey @dbakiu 👋🏻 Could you please check, what RR version you use? `./rr --version` command output.

Hey, here you go:
Roadrunner: `rr version 2023.1.1 (build time: 2023-04-20T12:40:33+0000, go1.20.3)`
PHP: 8.1.18

> Also, if that's possible, could you please provide debug (would be super cool) or at least error logs before/after this happens?
> 
> We tried to reproduce the bug, no luck. Sending hundreds of signals to the dozens of workflows - no luck. I think that these failures happened because of the WF worker restarts due to out of memory or some other exception.

Since the issue is only happening in production and we're unable to reproduce it locally, it is difficult to provide logs, apart from the error message that we got, which is a fairly generic one:
```{
  "message": "nondeterministic workflow: extra replay command for ScheduleActivityTask: (ActivityId:19, ActivityType:(Name:WorkflowClassNameX.ActivityNameY.activityMethodZ), TaskQueue:(Name:default, Kind:Normal), Input:(Payloads:[len=1]), ScheduleToCloseTimeout:0s, ScheduleToStartTimeout:0s, StartToCloseTimeout:5s, HeartbeatTimeout:0s, RequestEagerExecution:true)",
  "source": "GoSDK",
  "stackTrace": "",
  "encodedAttributes": null,
  "cause": null,
  "applicationFailureInfo": {
    "type": "historyMismatchError",
    "nonRetryable": false,
    "details": null
  }
}
```
Regarding your OOM suspicion, I took a look at our monitoring systems, and the memory usage on the pods has been consistently low. On average, it's around 10%, with a peak of 14% over the last 3 months. We're also monitoring the sticky cache size, and during that same period, it averages at about 220, with a maximum of 590, which is well under the default limit of 10000. Additionally, we have increased the sticky cache size to 20000, which was one advice we got from the Temporal support crew after the last batch of errors appeared.

**Comment by rustatian** [comment]
Thanks @dbakiu 👍🏻 
Seems that we've found the issue. On it.

**Comment by wolfy-j** [comment]
We are expecting that cumulative update by v2.5.3 and v2.5.4 will fix possible Signal issues.

**Comment by rustatian** [comment]
@dbakiu 👋🏻 
Have you had a chance to try out these new versions yet ?

**Comment by dbakiu** [comment]
Hi @rustatian,

We temporarily moved away from using activities in signals, so we weren't able to test whether the fix that was pushed as part of v2.5.3 and v.2.5.4 has addressed our issue. Since the bug is difficult to reproduce, as you saw yourself, it's also difficult to verify that it has been fixed. That being said, we will come up with a plan on reintroducing the activities and monitor the situation.

**Comment by roxblnfk** [comment]
Hello. Are there any updates on this issue?

**Comment by roxblnfk** [comment]
If the issue is still relevant, just reopen it.
