### ISSUE TITLE
[Feature Request] `EnableEagerStart` option in the  PHP `StartWorkflowOptions` structure

### ISSUE THREAD

**Issue by rustatian** [temporalio/sdk-php#344]
### Is your feature request related to a problem? Please describe.

RoadRunner-Temporal plugin supports the latest `SDK-GO`. So it's time to add a new `EnableEagerStart` option https://github.com/temporalio/sdk-go/releases/tag/v1.24.0

From release notes:

> Eager Workflow Dispatch (EWD) is a mechanism that minimizes the duration from starting a workflow to the processing of the first workflow task, making Temporal more suitable for latency sensitive applications. Eager workflow Dispatch can be enabled by setting EnableEagerStart in StartWorkflowOptions and if the server supports it and a local worker is available the task is fed directly to the worker.

**Comment by bergundy** [comment]
Note that this will require some extra work to allocate a workflow slot on a worker on the same task queue and delivering a workflow task to the workflow from the `StartWorfklowExecutionResponse`.
