### ISSUE TITLE
Changing data type during deserialization

### ISSUE THREAD

**Issue by windbridges** [temporalio/sdk-php#393]
I'm trying to return a DTO object containing an array of other DTO objects from an activity. Activity returns a DTO:

```
class ActivityResult {
   public int $count;
   /** @var ProductInfo[] */
   public array $items;
}
```

```
// inside workflow:
$result = yield $activity->getResult();
```

Further inside the workflow, it turns out that $result->items is not an array of ProductInfo, but an array of arrays. Each ProductInfo has been converted into an array with keys corresponding to the names of the object's properties.

Is this a bug or expected behavior?

**Comment by roxblnfk** [comment]
Hello @windbridges

The SDK uses its own Marshaller, which does not yet support type annotations.
Try to use `MarshalArray` attribute:

```php
class ActivityResult {
    public int $count;

    /** @var ProductInfo[] */
    #[MarshalArray(of: ProductInfo::class)]
    public array $items;
}
```

**Comment by roxblnfk** [comment]
I believe your issue has been resolved. For this reason, I am closing the Issue.
