### ISSUE TITLE
Make "ext-grpc" a composer requirement

### ISSUE THREAD

**Issue by dendemann** [temporalio/sdk-php#394]
Having ext-grpc installed seems to be a hard requirement. The samples documentation point out that gRPC PHP extension must be installed. When trying to instantiate a ServiceClient via `ServiceClient::create(...)` I got "Class 'Grpc\ChannelCredentials' not found" as the extension wasn't available on my setup. Anyway I would have expected that a composer install would have failed because of the missing extension.

When ext-grpc is a must have requirement I suggest adding it to the projects composer.json require section.

**Comment by roxblnfk** [comment]
Hello.
The gRPC extension is only required for client calls. The server part works without this extension.

Since both parts of the SDK (client and server) are in the same repository, I would prefer to add `ext-grpc` only to the `suggest` section.

**Comment by dendemann** [comment]
Hi. 
Thanks for explaining the details. Both your proposals combined are a good way to quickly find out what's wrong (without having to dig into the source)

**Comment by roxblnfk** [comment]
>  a good way to quickly find out what's wrong (without having to dig into the source)

 However, to quickly understand the problem, it is necessary to add the throwing of a proper exception in the client code.
Thank you for your feedback.
