### ISSUE TITLE
Is the WorkflowClient going to available in the php sdk soon? 

### ISSUE THREAD

**Issue by arengarajan** [temporalio/sdk-php#4]
Hi, 

I noticed that the php-sdk doesn't have a workflow client, similar to how [Java has one](https://github.com/temporalio/sdk-java/blob/master/temporal-sdk/src/main/java/io/temporal/client/WorkflowClient.java) (where you can also configure the namespace, etc.)

I know this SDK is a work in progress, but just wanted to check if I was missing something and if the client will be available soon/ is planned to be incorporated as part of this project. Thanks!

Anand

**Comment by wolfy-j** [comment]
Hi,

this SDK does have a Workflow client - Worker (we use different name due to different exection strategy). Task Queue will be exposed via it (currently it's internal).

**Comment by wolfy-j** [comment]
The WorkflowClient is available in a current SDK implementation and will go to the release.

**Comment by wolfy-j** [comment]
Hi, you can find examples of workflow client here: https://github.com/temporalio/samples-php
