### ISSUE TITLE
[Feature Request] Update Carbon to 3.*

### ISSUE THREAD

**Issue by Atantares** [temporalio/sdk-php#401]
### Is your feature request related to a problem?

While upgrading my Symfony 6.4 project I get an error from composer:
```
Problem 1
    - nesbot/carbon[2.66.0, ..., 2.72.3] require symfony/translation ^3.4 || ^4.0 || ^5.0 || ^6.0 -> found symfony/translation[v3.4.0, ..., v3.4.47, v4.0.0, ..., v4.4.47, v5.0.0, ..., v5.4.35, v6.0.0, ..., v6.4.4] but it conflicts with your root composer.json require (7.0.*).
    - temporal/sdk[v2.7.0, ..., v2.7.6] require nesbot/carbon ^2.66 -> satisfiable by nesbot/carbon[2.66.0, ..., 2.72.3].
    - Root composer.json requires temporal/sdk ^2.7.0 -> satisfiable by temporal/sdk[v2.7.0, ..., v2.7.6].
```

Carbon 3.0 supports Symfony 7
Commit: https://github.com/briannesbitt/Carbon/commit/1175d7d48aeb5d772b5c268e783df5a6a8336653

### Describe the solution you'd like

composer.json
```json
{
    "require": {
        "nesbot/carbon":"^3.0"
     }
}
```

**Comment by roxblnfk** [comment]
Hello. Thank you for opening the issue. The problem [is already known](https://temporalio.slack.com/archives/C01LK9FAMM0/p1707992253232579).
However, to upgrade the carbon version, it's necessary to remove the conflicting package "illuminate/support". Classes from this package are used in several places in the tests, and some work needs to be done to get rid of the excess.
I plan to return to this issue later. However, if you have some free time, feel free to open a PR with a fix.

**Comment by Atantares** [comment]
Got it, thanks @roxblnfk 
I'll try to look into this one. 
Is that a public Slack channel? If so, can I get an invitation?

**Comment by roxblnfk** [comment]
> Is that a public Slack channel? If so, can I get an invitation?

Sure

https://temporal.io/slack
