### ISSUE TITLE
[Feature Request] API key client option

### ISSUE THREAD

**Issue by cretz** [temporalio/sdk-php#410]
### Describe the solution you'd like

See https://github.com/temporalio/features/issues/426 and https://github.com/temporalio/sdk-go/pull/1409 for the ideal approach

**Comment by roxblnfk** [comment]
Starting with PHP SDK version 2.9.0, users can specify any metadata, including the authorization header.

```php
/** @var \Temporal\Client\WorkflowClient $workflowClient */

$workflowClient = $workflowClient->withMetadata('Authorization', ['Bearer <api-key>']);

// All the calls $workflow->* will be executed with the specified metadata.
$workflowClient->newWorkflowStub(MyWorkflow::class);
```

Do we really need to add extra syntactic sugar for this header?

**Comment by josh-berry** [comment]
I think it's a nice thing to have ergonomically, and it matches what the other SDKs do (or will do). So unless it's gonna cause some significant amount of ugliness, I personally think it's worth doing.
