### ISSUE TITLE
[Bug] Incorrect deadline verification in case of exception

### ISSUE THREAD

**Issue by kkosowski-p** [temporalio/sdk-php#431]
### What are you really trying to do?

Timeout/deadline should be correctly verified in case of ServiceClientException in https://github.com/temporalio/sdk-php/blob/master/src/Client/GRPC/BaseClient.php#L314

### Describe the bug

Comparison direction should be swapped. Now it checks if deadline is before current time, what should not be a trigger for timeout exception.

### Minimal Reproduction

Create WorkflowClientInterface with timeout 10secs. Create ActivityCompletionClientInterface with client. Run completeByToken() with not-existing token. TimeoutException will be thrown.

**Comment by roxblnfk** [comment]
Thanks!
Fixed with [v2.9.1](https://github.com/temporalio/sdk-php/releases/tag/v2.9.1)
