### ISSUE TITLE
example project not invoking activity

### ISSUE THREAD

**Issue by ashish-s** [temporalio/sdk-php#5]
hello,
I was trying to make the example project work for a small experiment, but  wasnt able to get the activity invoked.  I can explicitly see that the StartActivity is not implemented yet, is there a development version of this codebase where it is working ?

**Comment by SerafimArts** [comment]
Hello! This SDK is under development. We will announce separately as soon as there is a working version with working examples ready for testing.

**Comment by wolfy-j** [comment]
Hi, you can find working samples and instruction here: https://github.com/temporalio/samples-php
