### ISSUE TITLE
upsert Search Attribute

### ISSUE THREAD

**Issue by changwuf31** [temporalio/sdk-php#76]
Hi, thanks for the php sdk.
Is there any plan on adding upsert Search Attribute in the php sdk ?

**Comment by wolfy-j** [comment]
Hi, yes. We will add this attribute after the release, it’s quick to do.

**Comment by cv65kr** [comment]
@wolfy-j any updates?

**Comment by cv65kr** [comment]
@seregazhuk you can close this issue 😄
