### ISSUE TITLE
Improve service container

### ISSUE THREAD

**Issue by SerafimArts** [temporalio/sdk-php#88]
Service container and worker factory classes:
- https://github.com/temporalio/sdk-php/blob/a5a212793f1cb5555d692fb134c01242f8e6111c/src/Internal/ServiceContainer.php#L125
- https://github.com/temporalio/sdk-php/blob/a5a212793f1cb5555d692fb134c01242f8e6111c/src/WorkerFactory.php#L286

Should be rewritten using a clearer and more user-friendly approach (global PSR-11?).

We should think about solving this problem, because a certain set of services is also used in the client.

**Comment by wolfy-j** [comment]
Closing for now since the current structure is stable.
