### ISSUE TITLE
Integration issue with Laravel

### ISSUE THREAD

**Issue by tank-pooja** [temporalio/sdk-php#94]
Hi,
 I am trying to integrate temporal with Laravel 8.x, but not able to access Laravel facades inside the workflow or activity, exception is thrown from laravel
` RuntimeException: A facade root has not been set.`

**Comment by wolfy-j** [comment]
I would recommend starting working inside laravel command, where facade context is already set. However, I’d like to also recommend avoid using facades in Workflows, they might break the determinism of that code. Feel free to use them in Activities.

**Comment by tank-pooja** [comment]
Thanks @wolfy-j , it's working now.
