### ISSUE TITLE
[Bug] Non-retryable exceptions list in RetryOptions does not work as expected

### ISSUE THREAD

**Issue by kozlice** [temporalio/sdk-php#95]
**Describe the bug**
Non-retryable exceptions list in RetryOptions does not work as expected.

**To Reproduce**
Type hints (`@psalm-type ExceptionsList = array<class-string<\Throwable>>`) and documentation (https://docs.temporal.io/docs/php-retries) tell us to provide a list of class names:
```php
$retryOptions = RetryOptions::new()
    ->withNonRetryableExceptions([
        \InvalidArgumentException::class,
        \LogicException::class,
    ])
    ->withMaximumAttempts(3)
    ->withInitialInterval(new \DateInterval('PT5S'))
    ->withBackoffCoefficient(1)
;
```
Then I throw `RuntimeException` inside an activity method, which is not on the list. However, instead of an expected retry I saw this in Temporal web UI:
```
PanicError: assert(Assert::valuesInstanceOf($exceptions, \Throwable::class)) (type: AssertionError, retryable: true) 
```

**Expected behavior**
Process should respect the class list I provide.

**Reason**
The problem is with the `Temporal\Internal\Assert::valuesSubclassOf` method. PHP's `instanceof` won't work here:

```php

$v = \InvalidArgumentException::class;
$of = \Throwable::class;

var_dump($v instanceof $of); // false, because $v is just a string
var_dump(is_subclass_of($v, $of)); // true, it checks hierarchy internally
```

I'll submit a PR to fix this shortly.

**Comment by SerafimArts** [comment]
Fixed in #96
