### ISSUE TITLE
[Bug] PHP 7.4 docblock anotations don't work (or documentation missing?)

### ISSUE THREAD

**Issue by Rastusik** [temporalio/sdk-php#98]
Hi, I'm trying to run temporal-sdk with php 7.4 (which is minimum supported version according to composer.json), but the SDK is unable to parse my workflows because I'm not using PHP 8 style attributes, but older PHP 7.4 docblock style. 

**To Reproduce**
1. try to work with this workflow interface:
```
use Temporal\Workflow\WorkflowInterface;
use Temporal\Workflow\WorkflowMethod;

/**
 * @WorkflowInterface()
 */
interface SomeWorkflow
{
    /**
     * @return void
     * @WorkflowMethod(name="fork")
     */
    public function something();
}
```
4. When the workflow client tries to work with the mentioned worklfow, it throws this error: `Workflow class SomeWorkflow or one of his parents (i.e. class, interface or trait) must contain #[Temporal\Workflow\WorkflowInterface] attribute`

**Expected behavior**
Well, the attribute/annotation should be found if minimum supported PHP version is 7.4

**Comment by SerafimArts** [comment]
Hello!
1) Do you install a `doctrine/annotations` driver for annotation work?
2) Attributes work on any version of PHP.

**Comment by Rastusik** [comment]
Hi, yes, I have `doctrine/annotations:^1.12` installed

**Comment by SerafimArts** [comment]
Hmm, this is weird as this functionality has been tested by unit tests: https://github.com/temporalio/sdk-php/blob/master/tests/Unit/Declaration/DeclarationTestCase.php#L33

**Comment by Rastusik** [comment]
from what I've been able to find out it looks like the Spiral Attribute reader doesn't even use doctrine annotation reader

**Comment by Rastusik** [comment]
but the spiral FallbackAttributeReader is being used, and it looks lik it doesn't work properly

**Comment by SerafimArts** [comment]
> from what I've been able to find out it looks like the Spiral Attribute reader doesn't even use doctrine annotation reader

Used to read annotations if a dependency is installed: https://github.com/temporalio/sdk-php/blob/master/src/WorkerFactory.php#L299-L306

> but the spiral FallbackAttributeReader is being used, and it looks lik it doesn't work properly...

This is a PHP 8 "emulator" that allows you to read attributes on any version of the PHP.

**Comment by Rastusik** [comment]
btw I'm creating the Workflow client according to documentation: 
```
fn (): WorkflowClientInterface => WorkflowClient::create(
                ServiceClient::create($this->config->getTemporalHost())
            )
```

Maybe I should hack the dependencies somehow?

> Used to read annotations if a dependency is installed: https://github.com/temporalio/sdk-php/blob/master/src/WorkerFactory.php#L299-L306
> 

I haven't used the WorkerFactory yet, as the first step I'm trying to send a workflow to temporal, without any running workers

**Comment by Rastusik** [comment]
shouldn't the same decision be made here? https://github.com/temporalio/sdk-php/blob/master/src/Client/WorkflowClient.php#L57

**Comment by SerafimArts** [comment]
> I haven't used the WorkerFactory yet, as the first step I'm trying to send a workflow to temporal, without any running workers

Yeah, I think I get it now. You are using only the client, and there is only support for attributes. We seem to have found the problem.

**Comment by SerafimArts** [comment]
> shouldn't the same decision be made here?

Yeah! This is exactly the problematic section of the code.

**Comment by SerafimArts** [comment]
Thanks for the feedback!

Fixed in https://github.com/temporalio/sdk-php/releases/tag/v1.0.2

**Comment by Rastusik** [comment]
thanks for the prompt fix! :)
